module.exports = [
  {
    id: 'fdafdass',
    label: 'select field test',
    inputType: 'select',
    options: ['option1', 'option2', 'option3'],
    placeholder: 'option2',
    formID: '123',
    isRequired: true,
    position: 3,
  },
  {
    id: 'fffdsa',
    label: 'text input field test',
    inputType: 'textinput',
    options: undefined,
    placeholder: 'placeholder test',
    formID: '123',
    isRequired: true,
    position: 2,
  },
  {
    id: 'ccccfdsa',
    label: 'text area field test',
    inputType: 'textarea',
    options: undefined,
    placeholder: 'placeholder test',
    formID: '123',
    isRequired: true,
    position: 1,
  },
  {
    id: 'afdfsdfdasdfsa',
    label: 'Radios field test',
    inputType: 'radio',
    options: ['radio option1', 'carls jr', 'carls sr'],
    placeholder: 'carls sr',
    formID: '123',
    isRequired: true,
    position: 4,
  },
  {
    id: 'fdas',
    label: 'select field test',
    inputType: 'select',
    options: ['option1', 'option2', 'option3'],
    placeholder: 'option2',
    formID: '122',
    isRequired: true,
    position: 10,
  },
  {
    id: 'ff',
    label: 'text input field test',
    inputType: 'textinput',
    options: undefined,
    placeholder: 'placeholder test',
    formID: '122',
    isRequired: true,
    position: 3,
  },
  {
    id: 'cccc',
    label: 'text area field test',
    inputType: 'textarea',
    options: undefined,
    placeholder: 'placeholder test',
    formID: '122',
    isRequired: true,
    position: 2,
  },
  {
    id: 'afdfsda',
    label: 'Radios field test',
    inputType: 'radio',
    options: ['radio option1', 'carls jr', 'carls sr'],
    placeholder: 'carls sr',
    formID: '122',
    isRequired: true,
    position: 4,
  },
  {
    id: 'adnllk',
    label: 'Checkboxes field test',
    inputType: 'checkbox',
    options: ['Check mate', 'Check Pleaaaase', 'Check yo self'],
    placeholder: 'Check mate',
    formID: '122',
    isRequired: true,
    position: 5,
  },
  {
    id: 'adlkjlkjnbgh',
    label: 'select field test',
    inputType: 'select',
    options: ['option1', 'option2', 'option3'],
    placeholder: 'option2',
    formID: '122',
    isRequired: true,
    position: 6,
  },
  {
    id: 'addyryryr',
    label: 'text input field test',
    inputType: 'textinput',
    options: undefined,
    placeholder: 'placeholder test',
    formID: '122',
    isRequired: true,
    position: 7,
  },
  {
    id: 'adcyhnbgt',
    label: 'text area field test',
    inputType: 'textarea',
    options: undefined,
    placeholder: 'placeholder test',
    formID: '122',
    isRequired: true,
    position: 8,
  },
  {
    id: 'adbwerwer',
    label: 'Radios field test',
    inputType: 'radio',
    options: ['radio option1', 'carls jr', 'carls sr'],
    placeholder: 'carls sr',
    formID: '122',
    isRequired: true,
    position: 9,
  },
  {
    id: 'ad5555',
    label: 'This better be the first!!',
    inputType: 'checkbox',
    options: ['Check mate', 'Check Pleaaaase', 'Check yo self'],
    placeholder: 'Check mate',
    formID: '122',
    isRequired: true,
    position: 1,
  },
]
