module.exports = [
  {
    id: 'fdafdass',
    label: 'How long have you been making electronic music?',
    inputType: 'radio',
    options: ['Less than 1 year', 'Roughly 1 year', 'More than 1 year'],
    placeholder: '',
    formID: '123',
    isRequired: true,
    position: 2,
  },
  {
    id: 'fffdsa',
    label: 'Your Full Name',
    inputType: 'textinput',
    options: undefined,
    placeholder: 'Full Name',
    formID: '123',
    isRequired: true,
    position: 1,
  },
  {
    id: 'ccccfdsa',
    label: "Is there anything you'd like to focus on?",
    inputType: 'textarea',
    options: undefined,
    placeholder: 'ex.. Mixing Drums, or Vocalss',
    formID: '123',
    isRequired: true,
    position: 4,
  },
  {
    id: 'afdfsdfdasdfsa',
    label: 'Select your genree',
    inputType: 'select',
    options: [
      'House',
      'Ambient',
      'Dubstep',
      'Glitch',
      'Glitch Hop',
      'Funk',
      'Techno',
    ],
    placeholder: '',
    formID: '123',
    isRequired: true,
    position: 3,
  },
  //
  //
  //
  //
  //
  //
  //
  {
    id: 'fdas',
    label: 'Pick a shirt color',
    inputType: 'select',
    options: [
      'Red',
      'Green',
      'Purple',
      'Yellow',
      'Brown',
      'Blue',
      'Pink',
      'Black',
      'White',
    ],
    placeholder: '',
    formID: '122',
    isRequired: true,
    position: 7,
  },
  {
    id: 'ff',
    label: 'What is your Address',
    inputType: 'textarea',
    options: undefined,
    placeholder: '1155 40th ave, Vancouver\nBC\nT2M2P9',
    formID: '122',
    isRequired: true,
    position: 3,
  },
  {
    id: 'cccc',
    label: 'What is your Last Name?',
    inputType: 'textinput',
    options: undefined,
    placeholder: 'Last Name',
    formID: '122',
    isRequired: true,
    position: 2,
  },
  {
    id: 'afdfsda',
    label: 'What is your email',
    inputType: 'textinput',
    placeholder: 'example@email.com',
    formID: '122',
    isRequired: true,
    position: 4,
  },
  {
    id: 'adnllk',
    label: 'Diet (select all that apply)',
    inputType: 'checkbox',
    options: ['I am Vegan', 'I am Vegitarian', 'I am Gluten Free'],
    placeholder: '',
    formID: '122',
    isRequired: true,
    position: 5,
  },
  {
    id: 'adlkjlkjnbgh',
    label: 'What is your shirt size?',
    inputType: 'select',
    options: ['xs', 's', 'm', 'l', 'xl', 'xxl'],
    placeholder: '',
    formID: '122',
    isRequired: true,
    position: 6,
  },
  {
    id: 'adcyhnbgt',
    label: 'Why are you interested in Space Travel?',
    inputType: 'textarea',
    options: undefined,
    placeholder: 'please fill..',
    formID: '122',
    isRequired: true,
    position: 8,
  },
  {
    id: 'adbwerwer',
    label: 'Are you a Canadian Citizen?',
    inputType: 'radio',
    options: ['Yes', 'No'],
    placeholder: 'carls sr',
    formID: '122',
    isRequired: true,
    position: 9,
  },
  {
    id: 'ad5555',
    label: 'What is your First Name?',
    inputType: 'textinput',
    placeholder: 'First Name',
    formID: '122',
    isRequired: true,
    position: 1,
  },
]
